Vault decrypt do not erase existing content anymore
Now when vault decrypt a file, it does not erase any existing already decrypted
file if the content will be different.
If the content is different, the previous decrypted file stay as it was and the
decrypted file is stored in an other file.

diff --git a/bin/vault b/bin/vault
--- a/bin/vault
+++ b/bin/vault
@@ -10,6 +10,8 @@
 set -o pipefail
 
 USERID=${USERID:-$(id -u)}
+RED='\033[0;31m'
+NC='\033[0m' # No Color
 
 comment()   { sed 's|^|# |g'; }
 uncomment() { sed 's|^# ||g'; }
@@ -25,14 +27,29 @@ encrypt_file() {
 decrypt_file() {
     local encryptedFile=$1
     local decryptedFile=$2
+    local tempDecryptedFile=$decryptedFile
+
+    if [ -f $decryptedFile ]; then
+        tempDecryptedFile="$decryptedFile.$(date +%s).decrypted"
+    fi
 
     set +e
-    cat $encryptedFile | uncomment | openssl aes-256-cbc -d -a -k $PASSWORD -md md5 &> $decryptedFile
+    cat $encryptedFile | uncomment | openssl aes-256-cbc -d -a -k $PASSWORD -md md5 &> $tempDecryptedFile
     status=$?
     set -e
     if [[ $status -ne 0 ]]; then
-        mv $decryptedFile $decryptedFile.error
-        decryptedFile=$decryptedFile.error
+        mv $tempDecryptedFile $tempDecryptedFile.error
+        decryptedFile=$tempDecryptedFile.error
+        (>&2 printf "${RED}Could not decrypt $encryptedFile, partial decryption in $tempDecryptedFile.error\n$NC")
+    else
+        if cmp -s $tempDecryptedFile $decryptedFile; then
+           if [[ "$tempDecryptedFile" != "$decryptedFile" ]]; then
+               rm $tempDecryptedFile
+           fi
+        else
+            (>&2 printf "${RED}Decrypting $encryptedFile would override $decryptedFile content.${NC}\nDecrypting to $tempDecryptedFile instead\n")
+            decryptedFile=$tempDecryptedFile
+        fi
     fi
     chown $USERID:$USERID $decryptedFile && chmod 600 $decryptedFile || true
 }
